"""add app_settings table

Revision ID: 894dc66e4503
Revises: b6067ff4ba53
Create Date: 2026-02-13 21:08:57.407468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894dc66e4503'
down_revision = 'b6067ff4ba53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
