"""initial migration

Revision ID: 90d4c4b510d4
Revises: 
Create Date: 2026-01-29 01:25:03.602169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90d4c4b510d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('server', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('featured_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('listing_type', sa.String(length=50), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payment_reference', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id')
    )
    op.create_table('product_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.alter_column('permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('admin_roles_user_id_key'), type_='unique')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('ads_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('impressions', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])
        batch_op.drop_column('active')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('status')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('active')

    # Populate slugs for existing categories, then make column non-null and add unique index
    op.execute("""UPDATE categories SET slug = lower(regexp_replace(coalesce(name, ''), '[^a-z0-9]+', '-', 'gi')) WHERE slug IS NULL OR slug = '';""")
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user2_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user1_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user2_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('participants')
        batch_op.drop_column('last_message')

    with op.batch_alter_table('featured_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])
        batch_op.drop_column('active')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('status')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('media_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('media')
        batch_op.drop_column('read')
        batch_op.drop_column('message')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('type')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('read')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False))
        batch_op.add_column(sa.Column('buyer_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('seller_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receipt_url', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.drop_constraint(batch_op.f('orders_seller_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])
        batch_op.drop_column('product_price')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('notes')
        batch_op.drop_column('product_name')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('payment_confirmed')

    with op.batch_alter_table('otp_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=False, server_default='000000'))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')))
        batch_op.add_column(sa.Column('is_used', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_otp_logs_email'), ['email'], unique=False)
        batch_op.drop_column('otp')
        batch_op.drop_column('verified')
        batch_op.drop_column('expiry')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('slug', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('compare_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('is_in_stock', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pickup_location', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=False)
        batch_op.drop_constraint(batch_op.f('products_seller_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('products_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('capacity')
        batch_op.drop_column('media')
        batch_op.drop_column('review_count')
        batch_op.drop_column('amenities')
        batch_op.drop_column('availability')
        batch_op.drop_column('food_category')
        batch_op.drop_column('room_type')
        batch_op.drop_column('seller_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_urls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_hidden', sa.Boolean(), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('store_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('business_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('id_document_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('store_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('store_requests_store_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.drop_column('store_id')
        batch_op.drop_column('business_type')
        batch_op.drop_column('full_name')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('proof_document')
        batch_op.drop_column('store_address')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('banner_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('store_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('account_name', sa.String(length=200), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('stores_owner_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_stores_slug'), ['slug'], unique=True)
        batch_op.drop_column('business_type')
        batch_op.drop_column('total_products')
        batch_op.drop_column('bank_details')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('verified')
        batch_op.drop_column('subscription_expires')
        batch_op.drop_column('logo')
        batch_op.drop_column('banner')
        batch_op.drop_column('verified_at')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_reference', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')

    # First add password_hash as nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_seller', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_student_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)
        batch_op.drop_column('email_verified')

    # Copy existing password data to password_hash column
    op.execute("UPDATE users SET password_hash = password WHERE password_hash IS NULL;")

    # Now make password_hash NOT NULL and drop the old password column
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash', existing_type=sa.String(length=255), nullable=False)
        batch_op.drop_column('password')

    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['id'])
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('notes')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('payment_proof')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_proof', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('admin_notes')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_unique_constraint(batch_op.f('users_student_id_key'), ['student_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('is_seller')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('payment_reference')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('plan')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('banner', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_expires', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_products', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_stores_slug'))
        batch_op.create_unique_constraint(batch_op.f('stores_owner_id_key'), ['owner_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('account_name')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('store_type')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('slug')

    with op.batch_alter_table('store_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('store_address', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('proof_document', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('store_requests_store_id_fkey'), 'stores', ['store_id'], ['id'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('store_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('id_document_url')
        batch_op.drop_column('business_address')
        batch_op.drop_column('store_type')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_hidden')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('media_urls')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('room_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('food_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('amenities', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('products_category_id_fkey'), 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('products_seller_id_fkey'), 'users', ['seller_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.alter_column('product_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('total_orders')
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('is_active')
        batch_op.drop_column('pickup_location')
        batch_op.drop_column('is_in_stock')
        batch_op.drop_column('compare_price')
        batch_op.drop_column('slug')
        batch_op.drop_column('title')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('otp_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('otp', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_otp_logs_email'))
        batch_op.drop_column('expires_at')
        batch_op.drop_column('is_used')
        batch_op.drop_column('otp_code')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_confirmed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rejected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('orders_seller_id_fkey'), 'users', ['seller_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_column('receipt_url')
        batch_op.drop_column('seller_note')
        batch_op.drop_column('buyer_note')
        batch_op.drop_column('total_price')
        batch_op.drop_column('unit_price')
        batch_op.drop_column('store_id')
        batch_op.drop_column('order_number')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('is_read')
        batch_op.drop_column('data')
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('media', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_read')
        batch_op.drop_column('media_url')
        batch_op.drop_column('content')

    with op.batch_alter_table('featured_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_active')
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('participants', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user2_id')
        batch_op.drop_column('user1_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.alter_column('icon',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('slug')

    with op.batch_alter_table('ads_banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('impressions')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_active')
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('position')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('admin_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('admin_roles_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    op.drop_table('product_media')
    op.drop_table('product_categories')
    op.drop_table('featured_listings')
    op.drop_table('ad_requests')
    op.drop_table('reports')
    op.drop_table('activity_logs')
    op.drop_table('smtp_configs')
    # ### end Alembic commands ###
